version: '3'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./:/app"
    tty: true
    environment:
      TZ: Asia/Tokyo
      # FLASK_APP: ./app.py
    command: flask run --host 0.0.0.0 --port 5000
    # command: flask run --host 0.0.0.0 --port 5000 --debugger --reload
